//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InlineEditing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dominios
    {
        public int domDominioId { get; set; }
        public string domDescripcion { get; set; }
        public string domObservacion { get; set; }
        public bool domAnulado { get; set; }
        public Nullable<System.DateTime> domFechaCreacion { get; set; }
        public Nullable<int> empEmpleadoIdCreador { get; set; }
        public System.DateTime domFechaDesde { get; set; }
        public Nullable<System.DateTime> domFechaHasta { get; set; }
    }
}
